//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Javalib\lab.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class labParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		A=1, B=2, Sum=3, WS=4;
	public const int
		RULE_ab = 0;
	public static readonly string[] ruleNames = {
		"ab"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, "'+'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "A", "B", "Sum", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "lab.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static labParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public labParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public labParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class AbContext : ParserRuleContext {
		public ITerminalNode[] A() { return GetTokens(labParser.A); }
		public ITerminalNode A(int i) {
			return GetToken(labParser.A, i);
		}
		public ITerminalNode[] Sum() { return GetTokens(labParser.Sum); }
		public ITerminalNode Sum(int i) {
			return GetToken(labParser.Sum, i);
		}
		public ITerminalNode[] B() { return GetTokens(labParser.B); }
		public ITerminalNode B(int i) {
			return GetToken(labParser.B, i);
		}
		public AbContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ab; } }
	}

	[RuleVersion(0)]
	public AbContext ab() {
		AbContext _localctx = new AbContext(Context, State);
		EnterRule(_localctx, 0, RULE_ab);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 5;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << A) | (1L << B) | (1L << Sum))) != 0)) {
				{
				{
				State = 2;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << A) | (1L << B) | (1L << Sum))) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 7;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x6', '\v', '\x4', '\x2', '\t', '\x2', '\x3', '\x2', 
		'\a', '\x2', '\x6', '\n', '\x2', '\f', '\x2', '\xE', '\x2', '\t', '\v', 
		'\x2', '\x3', '\x2', '\x2', '\x2', '\x3', '\x2', '\x2', '\x3', '\x3', 
		'\x2', '\x3', '\x5', '\x2', '\n', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x4', '\x6', '\t', '\x2', '\x2', '\x2', '\x5', '\x4', '\x3', '\x2', '\x2', 
		'\x2', '\x6', '\t', '\x3', '\x2', '\x2', '\x2', '\a', '\x5', '\x3', '\x2', 
		'\x2', '\x2', '\a', '\b', '\x3', '\x2', '\x2', '\x2', '\b', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\t', '\a', '\x3', '\x2', '\x2', '\x2', '\x3', '\a',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
